### ISSUE TITLE
Add an installer for Apstra

### ISSUE THREAD

**Issue by ian-jarrett** [Juniper/nita#7]
Figure out how automate the deployment of Apstra by NITA.

**Comment by Adrian-STA** [comment]
We have looked into a way that NITA could help into the installation of Juniper Apstra, but Apstra is offered as an image preinstalled on a ubuntu linux that just needs to be instantiated in VMware, KVM, BUSYBOX, etc. So NITA would not bring any value to this. https://www.juniper.net/documentation/us/en/software/apstra4.1/apstra-install-upgrade/index.html
